services:
  redis:
    image: redis:8.0-M01-bookworm
    ports:
      - 6379:6379
    container_name: redis
  mongodb:
    image: mongodb/mongodb-community-server:7.0.2-ubi9
    container_name: mongodb
    ports:
      - 27017:27017
  se347-frontend:
    container_name: se347-frontend
    image: ghcr.io/ngodat0103/se347-frontend:0.1.0
    depends_on: [se347-backend]
    environment:
      BACKEND_ENDPOINT: ${BACKEND_ENDPOINT}
    ports:
      - 4200:4200
  se347-backend:
    container_name: se347-backend
    image: ghcr.io/ngodat0103/se347-backend:0.1.0
    depends_on: [mongodb, redis]
    environment:
      URL_MONGO_DB: ${URL_MONGO_DB}
      SECRET_TOKEN: ${SECRET_TOKEN}
      EXPIRESIN_TOKEN: ${EXPIRESIN_TOKEN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_EMAIL_CLIENT: ${FIREBASE_EMAIL_CLIENT}
      # MAIL_HOST: ${MAIL_HOST}
      # MAIL_USER: ${MAIL_USER}
      # MAIL_PASSWORD: ${MAIL_PASSWORD}
      # MAIL_FROM: ${MAIL_FROM}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "5000:5000"
