- name: Install Docker on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Install docker
      ansible.builtin.shell:
        creates: /usr/bin/docker
        cmd: |
          cd /tmp
          git clone https://github.com/ngodat0103/scripts.git
          chmod +x ./scripts/docker-installation.sh
          ./scripts/docker-installation.sh
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Clone se347 repository
      ansible.builtin.shell:
        creates: /opt/se347
        cmd: |
          mkdir -p /opt/se347
          cd /opt
          git clone https://github.com/ngodat0103/se347.git
    - name: Deploying app with docker-compose
      community.docker.docker_compose_v2:
        pull: always
        project_src: /opt/se347/backend
        profiles: [all]
        project_name: se347
        state: present
        recreate: always
        build: never
        remove_orphans: true
