services:
  postgresql:
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    profiles: ["infra","dev","all"]
    image: "bitnami/postgresql:16.4.0-debian-12-r23"
    ports:
      - "5432:5432"
    volumes:
      - bitnami_postgresql:/bitnami/postgresql
  se347-backend:
    profiles: [ "app","all" ]
    image: "ghcr.io/ngodat0103/se347-backend:dev-latest"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: 5000
        SERVICE_NAME: se347-backend
        VERSION: v1
    container_name: se347-backend
    networks: [ dev ]
    healthcheck:
     test: ["CMD","curl","http://localhost:5000/actuator/health","|","grep","UP"]
     interval: 10s
     timeout: 3s
     retries: 3
    depends_on:
      - postgresql
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: "local-dev"
      SPRING_DATA_MONGODB_DATABASE: "se347-db"
volumes:
  bitnami_postgresql:
    name: bitnami_postgresql
networks:
  dev:
    name: dev
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
          gateway: "172.21.0.1"