logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.github.ngodat0103.javabackup.service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
spring:
  data:
    mongodb:
      host: localhost
      database: se347-db
#      authentication-database: admin
#      username: dev
#      password: dev
      port: 27017