server.port: 5000
server:
  forward-headers-strategy: framework
  servlet:
    context-path: /api/v1
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - "optional:local-dev.yaml"
  application:
    name: se346-backend
springdoc:
  open-api:
    info:
      version: ${APP_VERSION}
      title: 'User service management'
      description: 'User service management'
      contact:
        url: 'https://github.com/ngodat0103'
        email: 'ngovuminhdat@gmail.com'
        name: 'datnvm'
  api-docs:
    path: /users/api-docs
  swagger-ui:
    path: /users/ui-docs
    use-root-path: true
