management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.github.ngodat0103.javabackup.service: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/user-management
    username: "dev"
    password: "dev"
